### ISSUE TITLE
issue when click to pay in table action see attached image

### ISSUE THREAD

**Issue by agaitan026** [tomatophp/filament-payments#3]
im trying to test payment and it shows this:

![image](https://github.com/user-attachments/assets/068438ae-a49e-4eda-b89c-49106a14a36c)

**Comment by 3x1io** [comment]
i think it's just a laravel error, your method `->ordersItems()` not exist on your $record!

**Comment by agaitan026** [comment]
got it i just added something like ->details('Payment test')
