### ISSUE TITLE
how to create return PaymentRequest::make(Order::class) Order class?

### ISSUE THREAD

**Issue by agaitan026** [tomatophp/filament-payments#5]
im following the doc for [#](https://filamentphp.com/plugins/3x1io-tomato-payments#use-payment-action)Use Payment Action

but im getting 

Class "App\Filament\Cliente\Resources\Order" not found

**Comment by agaitan026** [comment]
![image](https://github.com/user-attachments/assets/7d49bca4-9677-440f-98aa-799db1d1de3b)

**Comment by 3x1io** [comment]
`Order::class` can be any class connected to the payment, like if you want to charge customer wallet on this case you need to use `Wallet::class` where is the Model of the wallet

**Comment by agaitan026** [comment]
What if i dont have any class?

**Comment by 3x1io** [comment]
i think you must have a class, to handle your callback we handle it all to attach a class
