### ISSUE TITLE
created custom payment following example but didnt worked

### ISSUE THREAD

**Issue by agaitan026** [tomatophp/filament-payments#6]
getting this

![image](https://github.com/user-attachments/assets/521ce7d5-60e9-42ee-bc9c-3a8e24762067)

![image](https://github.com/user-attachments/assets/e9ecf893-96c5-44ae-b0f2-435493a0697c)

![image](https://github.com/user-attachments/assets/27761eba-da78-4fb8-8fc1-8f77a90442f2)

**Comment by agaitan026** [comment]
pd: if i put class inside TomatoPHP\\FilamentPayments\\Services\\Drivers it works

**Comment by 3x1io** [comment]
hi @agaitan026 fixed on the last version.
