### ISSUE TITLE
description Field Displays [object Object] When Editing Payment Gateway

### ISSUE THREAD

**Issue by CoconutDev-ops** [tomatophp/filament-payments#8]
When editing a payment gateway, the description field is returning [object Object] instead of the expected text.

![image](https://github.com/user-attachments/assets/1dc6becb-5fb7-4c75-b43d-75b063d11926)

Although the updates do save correctly to the database, reopening or re-editing the gateway still shows [object Object] in the description field.

I haven't had a chance to dig into the code base yet, but I’ll take a closer look when I have time. If I find a solution, I’ll be sure to share it.

**Comment by fadymondy** [comment]
hi @CoconutDev-ops thanks for report, we will fix this ASAP

**Comment by megoxv** [comment]
fixed on the last version thanks for your report.
